name: Audiobookshelf
version: "1.0.1"
slug: audiobookshelf
description: Audiobookshelf server for Home Assistant
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
ingress: true
panel_icon: mdi:book-open-variant
map:
  - media:rw
  - share:rw
options:
  port: 13378
schema:
  port: int
