name: Audiobookshelf
version: "1.0.4"
slug: audiobookshelf
description: Audiobookshelf server for Home Assistant
arch:
  - amd64
  - aarch64
startup: services
boot: auto
init: false
panel_icon: mdi:book-open-variant
webui: "http://[HOST]:[PORT:80]"
ports:
  80/tcp: 13378
ports_description:
  80/tcp: Web interface
map:
  - media:rw
  - share:rw
